/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export type Specs = {
  label?: string
  id?: string
}[]
export type OffersDeck = {
  image?: string | Image
  writeup?: {
    [k: string]: unknown
  }[]
  specs?: Specs
  buttons?: Buttons
  id?: string
}[]
export type FeaturesDeck = {
  image?: string | Image
  icon?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  id?: string
}[]
export type Buttons = {
  label?: string
  hrefSource?: 'doc' | 'href'
  doc?:
    | {
        relationTo: 'pages'
        value: string | Page
      }
    | {
        relationTo: 'posts'
        value: string | Post
      }
    | {
        relationTo: 'products'
        value: string | Product
      }
    | {
        relationTo: 'services'
        value: string | Service
      }
    | {
        relationTo: 'policies'
        value: string | Policy
      }
  href?: string
  id?: string
}[]
export type StatsDeck = {
  icon?: string
  title?: string
  value?: string
  id?: string
}[]
export type CartItems = {
  product: string | Product
  quantity: number
  variantLabel?: string
  variantId?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  id?: string
}[]
export type Links = {
  label?: string
  hrefSource?: 'doc' | 'href'
  doc?:
    | {
        relationTo: 'pages'
        value: string | Page
      }
    | {
        relationTo: 'posts'
        value: string | Post
      }
    | {
        relationTo: 'products'
        value: string | Product
      }
    | {
        relationTo: 'services'
        value: string | Service
      }
    | {
        relationTo: 'policies'
        value: string | Policy
      }
  href?: string
  id?: string
}[]
export type HeroBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  image: {
    exclude?: boolean
    position: 'relative' | 'background' | 'cover'
    class?: string
    className?: string
  }
  video: {
    exclude?: boolean
    position: 'relative' | 'background' | 'cover'
    class?: string
    className?: string
  }
  id?: string
}[]
export type CtaBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  image: {
    exclude?: boolean
    position: 'relative' | 'background' | 'cover'
    class?: string
    className?: string
  }
  video: {
    exclude?: boolean
    position: 'relative' | 'background' | 'cover'
    class?: string
    className?: string
  }
  id?: string
}[]
export type FeaturesBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  features: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    segment: {
      exclude?: boolean
      layout: 'col' | 'row'
      x: 'start' | 'center' | 'between'
      y: 'start' | 'center' | 'end'
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
    group: {
      exclude?: boolean
      layout: 'row' | 'col'
      x: 'stretch' | 'start' | 'center' | 'end'
      y: 'start' | 'center' | 'end'
      size?: 'small' | 'medium' | 'large'
      scheme?: 'light' | 'dark'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
    }
    buttons?: {
      exclude?: boolean
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
      id?: string
    }[]
    Icon: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  id?: string
}[]
export type ContentBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  image: {
    exclude?: boolean
    position: 'relative' | 'background' | 'cover'
    class?: string
    className?: string
  }
  prose: {
    exclude?: boolean
    class?: string
    className?: string
  }
  id?: string
}[]
export type ContactBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  channels: {
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    class?: string
    className?: string
  }
  list: {
    exclude?: boolean
    layout: 'col' | 'row'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  socials: {
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    size?: 'small' | 'medium' | 'large'
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    class?: string
    className?: string
  }
  form: {
    exclude?: boolean
    class?: string
    className?: string
  }
  id?: string
}[]
export type CategoriesBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  categories: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  id?: string
}[]
export type OffersBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  offers: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    segment: {
      exclude?: boolean
      layout: 'col' | 'row'
      x: 'start' | 'center' | 'between'
      y: 'start' | 'center' | 'end'
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
    list: {
      exclude?: boolean
      layout: 'col' | 'row'
      size?: 'small' | 'medium' | 'large'
      scheme?: 'light' | 'dark'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
    }
    specs: {
      exclude?: boolean
      class?: string
      className?: string
    }
    group: {
      exclude?: boolean
      layout: 'row' | 'col'
      x: 'stretch' | 'start' | 'center' | 'end'
      y: 'start' | 'center' | 'end'
      size?: 'small' | 'medium' | 'large'
      scheme?: 'light' | 'dark'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
    }
    buttons?: {
      exclude?: boolean
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
      id?: string
    }[]
  }
  id?: string
}[]
export type ImagesBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  gallery: {
    layout: 'grid' | 'carousel' | 'masonry' | 'row'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  id?: string
}[]
export type LogosBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  id?: string
}[]
export type PostsBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  posts: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    segment: {
      exclude?: boolean
      layout: 'col' | 'row'
      x: 'start' | 'center' | 'between'
      y: 'start' | 'center' | 'end'
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
    person: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  id?: string
}[]
export type ProductsBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  products: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  id?: string
}[]
export type ReviewsBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  reviews: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    segment: {
      exclude?: boolean
      layout: 'col' | 'row'
      x: 'start' | 'center' | 'between'
      y: 'start' | 'center' | 'end'
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    rating: {
      exclude?: boolean
      class?: string
      className?: string
    }
    person: {
      exclude?: boolean
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  id?: string
}[]
export type ServicesBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  services: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  id?: string
}[]
export type StatsBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  stats: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    segment: {
      exclude?: boolean
      layout: 'col' | 'row'
      x: 'start' | 'center' | 'between'
      y: 'start' | 'center' | 'end'
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
    group: {
      exclude?: boolean
      layout: 'row' | 'col'
      x: 'stretch' | 'start' | 'center' | 'end'
      y: 'start' | 'center' | 'end'
      size?: 'small' | 'medium' | 'large'
      scheme?: 'light' | 'dark'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
    }
    buttons?: {
      exclude?: boolean
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
      id?: string
    }[]
  }
  id?: string
}[]
export type EmployeesBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  segment: {
    exclude?: boolean
    layout: 'col' | 'row'
    x: 'start' | 'center' | 'between'
    y: 'start' | 'center' | 'end'
    hue?: 'base' | 'brand' | 'accent'
    size?: 'small' | 'medium' | 'large'
    class?: string
    className?: string
  }
  writeup: {
    exclude?: boolean
    class?: string
    className?: string
  }
  group: {
    exclude?: boolean
    layout: 'row' | 'col'
    x: 'stretch' | 'start' | 'center' | 'end'
    y: 'start' | 'center' | 'end'
    size?: 'small' | 'medium' | 'large'
    scheme?: 'light' | 'dark'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
  }
  buttons?: {
    exclude?: boolean
    look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
    hue?: 'base' | 'brand' | 'accent'
    class?: string
    className?: string
    id?: string
  }[]
  employees: {
    deck: {
      layout: 'grid' | 'carousel' | 'masonry' | 'row'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    card: {
      frame: 'panel' | 'fill'
      look: 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    segment: {
      exclude?: boolean
      layout: 'col' | 'row'
      x: 'start' | 'center' | 'between'
      y: 'start' | 'center' | 'end'
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
    group: {
      exclude?: boolean
      layout: 'row' | 'col'
      x: 'stretch' | 'start' | 'center' | 'end'
      y: 'start' | 'center' | 'end'
      size?: 'small' | 'medium' | 'large'
      scheme?: 'light' | 'dark'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
    }
    buttons?: {
      exclude?: boolean
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
      id?: string
    }[]
  }
  id?: string
}[]
export type BookingBlockSettings = {
  name: string
  section: {
    frame: 'fill' | 'float' | 'panel' | 'screen'
    look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
    layout: 'col' | 'row'
    y: 'start' | 'center' | 'end' | 'between'
    x: 'stretch' | 'center'
    order?: 'reverse' | 'switch'
    size?: 'small' | 'medium' | 'large'
    hue?: 'base' | 'brand' | 'accent'
    scheme?: 'light' | 'dark'
    class?: string
    className?: string
  }
  prose: {
    exclude?: boolean
    class?: string
    className?: string
  }
  id?: string
}[]

export interface Config {
  collections: {
    pages: Page
    posts: Post
    services: Service
    products: Product
    categories: Category
    brands: Brand
    policies: Policy
    reviews: Review
    images: Image
    orders: Order
    customers: Customer
    employees: Employee
    users: User
    forms: Form
    submissions: Submission
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  globals: {
    company: Company
    header: Header
    footer: Footer
    cta: Cta
    commerce: Commerce
    permissions: Permissions
    settings: Settings
  }
}
export interface Page {
  id: string
  slug?: string
  path?: string
  url?: string
  type: 'blocks' | 'rich'
  blocks?: (
    | CategoriesBlock
    | ContactBlock
    | ContentBlock
    | CtaBlock
    | FeaturesBlock
    | HeroBlock
    | ImagesBlock
    | LogosBlock
    | OffersBlock
    | PostsBlock
    | ProductsBlock
    | ReviewsBlock
    | ServicesBlock
    | WebflowBlock
    | StatsBlock
    | EmployeesBlock
    | BookingBlock
  )[]
  rich?: {
    [k: string]: unknown
  }[]
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface CategoriesBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  categories: CategoriesDeck
  id?: string
  blockName?: string
  blockType: 'categories'
}
export interface Post {
  id: string
  slug?: string
  path?: string
  url?: string
  image?: string | Image
  title?: string
  description?: string
  rich?: {
    [k: string]: unknown
  }[]
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface Image {
  id: string
  alt?: string
  updatedAt: string
  createdAt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  sizes?: {
    w640?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
    w2560?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
  }
}
export interface Product {
  id: string
  slug?: string
  path?: string
  url?: string
  title?: string
  description?: string
  price?: number
  prose?: {
    [k: string]: unknown
  }[]
  images?: {
    image: string | Image
    id?: string
  }[]
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  categories?: string[] | Category[]
  brand?: string | Brand
  stripeDefaultPrice?: string
  stripeID?: string
  skipSync?: boolean
  updatedAt: string
  createdAt: string
}
export interface Category {
  id: string
  slug?: string
  path?: string
  url?: string
  image?: string | Image
  title?: string
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface Brand {
  id: string
  slug?: string
  path?: string
  url?: string
  title?: string
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface Service {
  id: string
  title?: string
  description?: string
  image?: string | Image
  slug?: string
  path?: string
  url?: string
  type: 'blocks' | 'rich'
  blocks?: (
    | ContentBlock
    | CtaBlock
    | HeroBlock
    | OffersBlock
    | ReviewsBlock
    | ServicesBlock
    | FeaturesBlock
  )[]
  rich?: {
    [k: string]: unknown
  }[]
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface ContentBlock {
  setting?: string
  image?: string | Image
  prose?: {
    [k: string]: unknown
  }[]
  id?: string
  blockName?: string
  blockType: 'content'
}
export interface CtaBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  image?: string | Image
  mediaSource?: 'video' | 'image'
  video?: string
  id?: string
  blockName?: string
  blockType: 'cta'
}
export interface HeroBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  mediaSource?: 'video' | 'image'
  video?: string
  image?: string | Image
  id?: string
  blockName?: string
  blockType: 'hero'
}
export interface OffersBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  offers: OffersDeck
  id?: string
  blockName?: string
  blockType: 'offers'
}
export interface ReviewsBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  reviews: ReviewsDeck
  id?: string
  blockName?: string
  blockType: 'reviews'
}
export interface ReviewsDeck {
  source: 'all' | 'docs'
  docs?: string[] | Review[]
}
export interface Review {
  id: string
  title?: string
  description?: string
  image?: string | Image
  rating?: number
  person?: Person
  author?: {
    name?: string
    tagline?: string
    avatar?: string | Image
  }
  blocks?: (
    | ContactBlock
    | ContentBlock
    | CtaBlock
    | HeroBlock
    | PostsBlock
    | ProductsBlock
    | ReviewsBlock
    | ServicesBlock
  )[]
  rich?: {
    [k: string]: unknown
  }[]
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface Person {
  name?: string
  label?: string
  avatar?: string | Image
}
export interface ContactBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  form: string | Form
  id?: string
  blockName?: string
  blockType: 'contact'
}
export interface Form {
  id: string
  title: string
  fields?: (
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: string
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'text'
      }
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: string
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'textarea'
      }
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: string
        options?: {
          label: string
          value: string
          id?: string
        }[]
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'select'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'email'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'state'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'country'
      }
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'number'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        defaultValue?: boolean
        id?: string
        blockName?: string
        blockType: 'checkbox'
      }
    | {
        message?: {
          [k: string]: unknown
        }[]
        id?: string
        blockName?: string
        blockType: 'message'
      }
  )[]
  submitButtonLabel?: string
  confirmationType?: 'message' | 'redirect'
  confirmationMessage: {
    [k: string]: unknown
  }[]
  redirect?: {
    url: string
  }
  emails?: {
    emailTo?: string
    cc?: string
    bcc?: string
    replyTo?: string
    emailFrom?: string
    subject: string
    message?: {
      [k: string]: unknown
    }[]
    id?: string
  }[]
  updatedAt: string
  createdAt: string
}
export interface PostsBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  posts: PostsDeck
  id?: string
  blockName?: string
  blockType: 'posts'
}
export interface PostsDeck {
  source: 'all' | 'docs'
  docs?: string[] | Post[]
}
export interface ProductsBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  products: ProductsDeck
  id?: string
  blockName?: string
  blockType: 'products'
}
export interface ProductsDeck {
  source: 'all' | 'docs'
  docs?: string[] | Product[]
}
export interface ServicesBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  services: ServicesDeck
  id?: string
  blockName?: string
  blockType: 'services'
}
export interface ServicesDeck {
  source: 'all' | 'docs'
  docs?: string[] | Service[]
}
export interface FeaturesBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  features: FeaturesDeck
  id?: string
  blockName?: string
  blockType: 'features'
}
export interface Policy {
  id: string
  slug?: string
  path?: string
  url?: string
  title?: string
  rich?: {
    [k: string]: unknown
  }[]
  meta?: {
    title?: string
    description?: string
    image?: string | Image
  }
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface CategoriesDeck {
  source: 'all' | 'docs'
  docs?: string[] | Category[]
}
export interface ImagesBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  images?: {
    image: string | Image
    id?: string
  }[]
  id?: string
  blockName?: string
  blockType: 'images'
}
export interface LogosBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  id?: string
  blockName?: string
  blockType: 'logos'
}
export interface WebflowBlock {
  html?: string
  css?: string
  images?: {
    image: string | Image
    id?: string
  }[]
  id?: string
  blockName?: string
  blockType: 'webflow'
}
export interface StatsBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  stats: StatsDeck
  id?: string
  blockName?: string
  blockType: 'stats'
}
export interface EmployeesBlock {
  setting?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  employees: EmployeesDeck
  id?: string
  blockName?: string
  blockType: 'employees'
}
export interface EmployeesDeck {
  source: 'all' | 'docs'
  docs?: string[] | Employee[]
}
export interface Employee {
  id: string
  image?: string | Image
  name?: string
  tagline?: string
  description?: string
  socials?: {
    social?:
      | 'facebook'
      | 'twitter'
      | 'instagram'
      | 'linkedin'
      | 'snapchat'
      | 'youtube'
      | 'tiktok'
      | 'pinterest'
    link?: string
    id?: string
  }[]
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface BookingBlock {
  setting?: string
  callLink?: string
  prose?: {
    [k: string]: unknown
  }[]
  id?: string
  blockName?: string
  blockType: 'booking'
}
export interface Order {
  id: string
  orderStatus?: 'unfulfilled' | 'fulfilled' | 'completed' | 'cancelled'
  customer?: string | Customer
  email?: string
  products?: {
    product?: string | Product
    quantity?: number
    id?: string
  }[]
  updatedAt: string
  createdAt: string
}
export interface Customer {
  id: string
  name?: string
  adressLineOne?: string
  adressLineTwo?: string
  country?: string
  city?: string
  postalCode?: string
  number?: number
  cart?: {
    items?: CartItems
    total?: number
  }
  stripeID?: string
  skipSync?: boolean
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password: string
}
export interface User {
  id: string
  roles?: ('admin' | 'ai' | 'developer' | 'designer' | 'writer')[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password: string
}
export interface Submission {
  id: string
  form: string | Form
  submissionData?: {
    field: string
    value: string
    id?: string
  }[]
  updatedAt: string
  createdAt: string
}
export interface PayloadPreference {
  id: string
  user:
    | {
        relationTo: 'customers'
        value: string | Customer
      }
    | {
        relationTo: 'users'
        value: string | User
      }
  key?: string
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
export interface PayloadMigration {
  id: string
  name?: string
  batch?: number
  updatedAt: string
  createdAt: string
}
export interface Company {
  id: string
  name?: string
  description?: string
  logo?: string | Image
  icon?: string | Image
  kvk?: number
  channels?: {
    email?: string
    phone?: number
    whatsapp?: number
    address?: string
  }
  socials?: {
    social?:
      | 'facebook'
      | 'twitter'
      | 'instagram'
      | 'linkedin'
      | 'snapchat'
      | 'youtube'
      | 'tiktok'
      | 'pinterest'
    link?: string
    id?: string
  }[]
  updatedAt?: string
  createdAt?: string
}
export interface Header {
  id: string
  links?: Links
  buttons?: Buttons
  updatedAt?: string
  createdAt?: string
}
export interface Footer {
  id: string
  columns?: {
    heading?: string
    links?: Links
    id?: string
  }[]
  policies?: string[] | Policy[]
  updatedAt?: string
  createdAt?: string
}
export interface Cta {
  id: string
  blockType?: string
  writeup?: {
    [k: string]: unknown
  }[]
  buttons?: Buttons
  image?: string | Image
  mediaSource?: 'video' | 'image'
  video?: string
  updatedAt?: string
  createdAt?: string
}
export interface Commerce {
  id: string
  currency?: 'eur'
  paymentMethods?: ('ideal' | 'card' | 'klarna')[]
  shippingRate?: number
  allowedCountries?: ('CH' | 'NL' | 'GB')[]
  succesUrl?: string
  failUrl?: string
  updatedAt?: string
  createdAt?: string
}
export interface Permissions {
  id: string
  collections: {
    posts?: boolean
    services?: boolean
    products?: boolean
    categories?: boolean
    reviews?: boolean
  }
  globals: {
    header?: boolean
    cta?: boolean
    footer?: boolean
  }
  _status?: 'draft' | 'published'
  updatedAt?: string
  createdAt?: string
}
export interface Settings {
  id: string
  theme: {
    colors: {
      base: 'gray' | 'mauve' | 'slate' | 'sage' | 'olive' | 'sand'
      brand:
        | 'tomato'
        | 'red'
        | 'ruby'
        | 'crimson'
        | 'pink'
        | 'plum'
        | 'purple'
        | 'violet'
        | 'iris'
        | 'indigo'
        | 'blue'
        | 'cyan'
        | 'teal'
        | 'jade'
        | 'green'
        | 'grass'
        | 'bronze'
        | 'gold'
        | 'brown'
        | 'orange'
        | 'amber'
        | 'yellow'
        | 'lime'
        | 'mint'
        | 'sky'
      accent:
        | 'tomato'
        | 'red'
        | 'ruby'
        | 'crimson'
        | 'pink'
        | 'plum'
        | 'purple'
        | 'violet'
        | 'iris'
        | 'indigo'
        | 'blue'
        | 'cyan'
        | 'teal'
        | 'jade'
        | 'green'
        | 'grass'
        | 'bronze'
        | 'gold'
        | 'brown'
        | 'orange'
        | 'amber'
        | 'yellow'
        | 'lime'
        | 'mint'
        | 'sky'
      scheme: 'light' | 'dark'
      texture: 'solid' | 'translucent'
      contrast: boolean
    }
    fonts: {
      heading: {
        family: string
        weight:
          | 'thin'
          | 'extralight'
          | 'light'
          | 'normal'
          | 'medium'
          | 'semibold'
          | 'bold'
          | 'extrabold'
          | 'black'
        italic?: boolean
        class?: string
        className?: string
      }
      subheading: {
        family: string
        weight:
          | 'thin'
          | 'extralight'
          | 'light'
          | 'normal'
          | 'medium'
          | 'semibold'
          | 'bold'
          | 'extrabold'
          | 'black'
        italic?: boolean
        class?: string
        className?: string
      }
      text: {
        family: string
        weight:
          | 'thin'
          | 'extralight'
          | 'light'
          | 'normal'
          | 'medium'
          | 'semibold'
          | 'bold'
          | 'extrabold'
          | 'black'
        italic?: boolean
        class?: string
        className?: string
      }
      button: {
        family: string
        weight:
          | 'thin'
          | 'extralight'
          | 'light'
          | 'normal'
          | 'medium'
          | 'semibold'
          | 'bold'
          | 'extrabold'
          | 'black'
        italic?: boolean
        class?: string
        className?: string
      }
    }
    sizes: {
      scale: number
      rounded: 'none' | 'tiny' | 'small' | 'medium' | 'large'
    }
  }
  elements: {
    writeup: {
      exclude?: boolean
      class?: string
      className?: string
    }
    buttons?: {
      exclude?: boolean
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      hue?: 'base' | 'brand' | 'accent'
      class?: string
      className?: string
      id?: string
    }[]
    links: {
      exclude?: boolean
      hue?: 'base' | 'brand' | 'accent'
      size?: 'small' | 'medium' | 'large'
      class?: string
      className?: string
    }
    channels: {
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      class?: string
      className?: string
    }
    collapsibles: {
      exclude?: boolean
      class?: string
      className?: string
    }
    image: {
      exclude?: boolean
      position: 'relative' | 'background' | 'cover'
      class?: string
      className?: string
    }
    person: {
      exclude?: boolean
      class?: string
      className?: string
    }
    rating: {
      exclude?: boolean
      class?: string
      className?: string
    }
    socials: {
      hue?: 'base' | 'brand' | 'accent'
      scheme?: 'light' | 'dark'
      size?: 'small' | 'medium' | 'large'
      look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
      class?: string
      className?: string
    }
    specs: {
      exclude?: boolean
      class?: string
      className?: string
    }
  }
  blocks: {
    hero?: HeroBlockSettings
    cta?: CtaBlockSettings
    features?: FeaturesBlockSettings
    content?: ContentBlockSettings
    contact?: ContactBlockSettings
    categories?: CategoriesBlockSettings
    offers?: OffersBlockSettings
    images?: ImagesBlockSettings
    logos?: LogosBlockSettings
    posts?: PostsBlockSettings
    products?: ProductsBlockSettings
    reviews?: ReviewsBlockSettings
    services?: ServicesBlockSettings
    stats?: StatsBlockSettings
    employees?: EmployeesBlockSettings
    booking?: BookingBlockSettings
  }
  globals: {
    header: {
      header: {
        frame: 'fill' | 'float' | 'panel'
        look: 'outline' | 'surface' | 'soft'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
      list: {
        exclude?: boolean
        layout: 'col' | 'row'
        size?: 'small' | 'medium' | 'large'
        scheme?: 'light' | 'dark'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
      }
      links: {
        exclude?: boolean
        hue?: 'base' | 'brand' | 'accent'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
      group: {
        exclude?: boolean
        layout: 'row' | 'col'
        x: 'stretch' | 'start' | 'center' | 'end'
        y: 'start' | 'center' | 'end'
        size?: 'small' | 'medium' | 'large'
        scheme?: 'light' | 'dark'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
      }
      buttons?: {
        exclude?: boolean
        look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
        id?: string
      }[]
    }
    footer: {
      footer: {
        frame: 'fill' | 'float' | 'panel'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
      }
      list: {
        exclude?: boolean
        layout: 'col' | 'row'
        size?: 'small' | 'medium' | 'large'
        scheme?: 'light' | 'dark'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
      }
      links: {
        exclude?: boolean
        hue?: 'base' | 'brand' | 'accent'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
      group: {
        exclude?: boolean
        layout: 'row' | 'col'
        x: 'stretch' | 'start' | 'center' | 'end'
        y: 'start' | 'center' | 'end'
        size?: 'small' | 'medium' | 'large'
        scheme?: 'light' | 'dark'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
      }
      channels: {
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
        class?: string
        className?: string
      }
      socials: {
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        size?: 'small' | 'medium' | 'large'
        look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
        class?: string
        className?: string
      }
    }
    cta: {
      section: {
        frame: 'fill' | 'float' | 'panel' | 'screen'
        look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
        layout: 'col' | 'row'
        y: 'start' | 'center' | 'end' | 'between'
        x: 'stretch' | 'center'
        order?: 'reverse' | 'switch'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
      segment: {
        exclude?: boolean
        layout: 'col' | 'row'
        x: 'start' | 'center' | 'between'
        y: 'start' | 'center' | 'end'
        hue?: 'base' | 'brand' | 'accent'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
      writeup: {
        exclude?: boolean
        class?: string
        className?: string
      }
      group: {
        exclude?: boolean
        layout: 'row' | 'col'
        x: 'stretch' | 'start' | 'center' | 'end'
        y: 'start' | 'center' | 'end'
        size?: 'small' | 'medium' | 'large'
        scheme?: 'light' | 'dark'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
      }
      buttons?: {
        exclude?: boolean
        look: 'solid' | 'soft' | 'surface' | 'outline' | 'ghost'
        hue?: 'base' | 'brand' | 'accent'
        class?: string
        className?: string
        id?: string
      }[]
      image: {
        exclude?: boolean
        position: 'relative' | 'background' | 'cover'
        class?: string
        className?: string
      }
      video: {
        exclude?: boolean
        position: 'relative' | 'background' | 'cover'
        class?: string
        className?: string
      }
    }
  }
  collections: {
    posts: {
      section: {
        frame: 'fill' | 'float' | 'panel' | 'screen'
        look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
        layout: 'col' | 'row'
        y: 'start' | 'center' | 'end' | 'between'
        x: 'stretch' | 'center'
        order?: 'reverse' | 'switch'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
      segment: {
        exclude?: boolean
        layout: 'col' | 'row'
        x: 'start' | 'center' | 'between'
        y: 'start' | 'center' | 'end'
        hue?: 'base' | 'brand' | 'accent'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
      writeup: {
        exclude?: boolean
        class?: string
        className?: string
      }
      image: {
        exclude?: boolean
        position: 'relative' | 'background' | 'cover'
        class?: string
        className?: string
      }
    }
    products: {
      section: {
        frame: 'fill' | 'float' | 'panel' | 'screen'
        look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
        layout: 'col' | 'row'
        y: 'start' | 'center' | 'end' | 'between'
        x: 'stretch' | 'center'
        order?: 'reverse' | 'switch'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
      segment: {
        exclude?: boolean
        layout: 'col' | 'row'
        x: 'start' | 'center' | 'between'
        y: 'start' | 'center' | 'end'
        hue?: 'base' | 'brand' | 'accent'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
      writeup: {
        exclude?: boolean
        class?: string
        className?: string
      }
    }
    categories: {
      section: {
        frame: 'fill' | 'float' | 'panel' | 'screen'
        look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
        layout: 'col' | 'row'
        y: 'start' | 'center' | 'end' | 'between'
        x: 'stretch' | 'center'
        order?: 'reverse' | 'switch'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
      segment: {
        exclude?: boolean
        layout: 'col' | 'row'
        x: 'start' | 'center' | 'between'
        y: 'start' | 'center' | 'end'
        hue?: 'base' | 'brand' | 'accent'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
      writeup: {
        exclude?: boolean
        class?: string
        className?: string
      }
      deck: {
        layout: 'grid' | 'carousel' | 'masonry' | 'row'
        size?: 'small' | 'medium' | 'large'
        class?: string
        className?: string
      }
    }
    reviews: {
      section: {
        frame: 'fill' | 'float' | 'panel' | 'screen'
        look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
        layout: 'col' | 'row'
        y: 'start' | 'center' | 'end' | 'between'
        x: 'stretch' | 'center'
        order?: 'reverse' | 'switch'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
    }
    services: {
      section: {
        frame: 'fill' | 'float' | 'panel' | 'screen'
        look: 'ghost' | 'outline' | 'soft' | 'surface' | 'solid'
        layout: 'col' | 'row'
        y: 'start' | 'center' | 'end' | 'between'
        x: 'stretch' | 'center'
        order?: 'reverse' | 'switch'
        size?: 'small' | 'medium' | 'large'
        hue?: 'base' | 'brand' | 'accent'
        scheme?: 'light' | 'dark'
        class?: string
        className?: string
      }
    }
  }
  _status?: 'draft' | 'published'
  updatedAt?: string
  createdAt?: string
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
