export * from './categoriesDeck'
export * from './employeesDeck'
export * from './featuresDeck'
export * from './offersDeck'
export * from './postsDeck'
export * from './reviewsDeck'
export * from './servicesDeck'
export * from './statsDeck'
